### ISSUE TITLE
Song title not showing up in Spotify

### ISSUE THREAD

**Issue by cbxsn** [MrGVSV/mybar#3]
When I listen to this song (and many others), the title doesn't show in the Spotify widget. It's just like `{{album_art}} - {{artist}} {{time_elapsed}}`

https://open.spotify.com/track/1LnLlXdoJ6UYFlWKe57nOz?si=2yn_B19nSxaMGh-xSeK9Bg

**Comment by timhradil** [comment]
This is due to a bug in the logic for shortening the song. I put in a pull request to fix this here: https://github.com/MrGVSV/mybar/pull/4.

**Comment by MrGVSV** [comment]
Fixed by #5
